### ISSUE TITLE
BooleanField Default Value Not Honored

### ISSUE THREAD

**Issue by SoundsSerious** [wtforms/wtforms#738] opened 2022-04-24 04:35 UTC
Using Python 3.8 with WTForms == 3.0.1

It seems pretty clear the default input for BooleanField is broken

Doesn't matter what the default is, not having input for the field will result in False

From Field.process():
```
        if formdata is not None:
            if self.name in formdata:
                self.raw_data = formdata.getlist(self.name)
            else:
                self.raw_data = []
                
            try:
                self.process_formdata(self.raw_data)  #< With no input this wil be []
```

In Boolean Field
```
    def process_formdata(self, valuelist):
        if not valuelist or valuelist[0] in self.false_values:
            self.data = False #NO INPUT ENDS UP HERE!
        else:
            self.data = True
```

Looking at the tests these seem broken too:
```
def test_defaults(): #SHOWN FOR REFERENCE
    # Test with no post data to make sure defaults work
    form = BoringForm()
    assert form.bool1.raw_data is None
    assert form.bool1.data is False
    assert form.bool2.data is True

def test_with_postdata():
    form = BoringForm(DummyPostData(bool1=["a"]))
    assert form.bool1.raw_data == ["a"]
    assert form.bool1.data is True #Why! a isn't boolean
    form = BoringForm(DummyPostData(bool1=["false"], bool2=["false"]))
    assert form.bool1.data is False 
    assert form.bool2.data is True #WTF
```

Its clear to see that whenever the value isn't input it will be false.

The simplest change could be:

```    
def process_formdata(self, valuelist):
        if len(valuelist)==0:
            self.data = self.default_value
        elif valuelist[0] in self.false_values:
            self.data = False
        else:
            self.data = True
```

But to prevent any ambiguity in form parsing this is how BooleanField should work:

Input:
```
BooleanField( <normal args>, default:bool = False, true_values=None, false_values=None)
```

Parsing:
```
def process_formdata(self, valuelist):
        if len(valuelist)==0:
            self.data = self.default_value
        elif valuelist[0] in self.false_values:
            self.data = False
       elif valuelist[0] in self.true_values:
            self.data = True
       else:
             #Print warning!
             self.data = self.default_value
 ```

**Comment by davidism** [comment] 2022-04-24 04:41
Duplicate of #402

**Comment by SoundsSerious** [comment] 2022-04-24 04:42
@davidism this seems to be a completely separate issue? Did you even read the code exceprts?

**Closed by davidism** 2022-04-24 04:41 UTC

**Comment by SoundsSerious** [comment] 2022-04-24 04:43
@davidism  Its completely clear that the code will not work as intended, why don't you leave the issue open so people can comment

**Comment by SoundsSerious** [comment] 2022-04-24 04:46
No Input = False, whats the point of having a default?

**Comment by SoundsSerious** [comment] 2022-04-24 05:00
@davidism 

Here is a non broken implementation of boolean

```
class BooleanField(Field):
    """
    REPLACE ISSUES WITH wtform.BooleanField
    Represents an ``<input type="checkbox">``. Set the ``checked``-status by using the
    ``default``-option. Any value for ``default``, e.g. ``default="checked"`` puts
    ``checked`` into the html-element and sets the ``data`` to ``True``

    :param false_values:
        If provided, a sequence of strings each of which is an exact match
        string of what is considered a "false" value. Defaults to the tuple
        ``(False, 'false', '',)``
    """
    widget = widgets.CheckboxInput()
    false_values = (False, 'false', 'no','n')
    true_values = (True,'true','yes','y')

    def __init__(self, label=None, validators=None, false_values=None, true_values=None, **kwargs):
        if 'default' in kwargs:
            default = kwargs['default']
            assert isinstance(default,bool)
            self.default=default
            
        super(BooleanField, self).__init__(label, validators, **kwargs)
        if false_values is not None:
            self.false_values = false_values

        if true_values is not None:
            self.true_values = true_values

    def process_data(self, value):
        self.data = bool(value)

    def process_formdata(self, valuelist):
        if len(valuelist)==0:
            self.data = self.default 
        elif valuelist[0] in self.false_values:
            self.data = False
        elif valuelist[0] in self.true_values:
                self.data = True
        else:
            #Print warning!
            self.data = self.default

    def _value(self):
        if self.raw_data:
            return str(self.raw_data[0])
        else:
            return 'y'
```
