### ISSUE TITLE
present value of BooleanField is ignored

### ISSUE THREAD

**Issue by asch99** [wtforms/wtforms#414] opened 2018-06-18 13:33 UTC
`BooleanField.process_formdata` overrides the present value of `self.data` even if an empty `valuelist` is passed. The same problem for `StringField` was fixed in commit 3708fc4 by checking `if self.data is None`.

proposed fix:

```python
    def process_formdata(self, valuelist):
        if valuelist and not (valuelist[0] in self.false_values):
            self.data = True
        elif self.data is None:
            self.data = False
```

related to #401 (OK in 2.1, bug in 2.2, 2.2.1)

**Comment by davidism** [comment] 2018-06-18 15:05
This is a boolean field, not a tristate field. `None` is not a valid value for data.

**Comment by davidism** [comment] 2018-06-24 16:21
This breaks in the opposite direction now: if a checkbox is unchecked, and a default of `True` was passed in, the value is not set to `False`. This is because HTML checkboxes are weird and don't submit anything when they're unchecked.

**Comment by davidism** [comment] 2018-06-24 16:59
See #402 for a discussion on the issue here. The easiest solution is to only pass `formdata` if you've actually submitted the form, by checking that the method is `POST` and that a name from the form (that's not a boolean) is in the form data.

```python
if request.method == "POST" and 'known_field' in request.form:
    form = ExampleForm(request.form)
    if form.validate():
        ...
else:
    form = ExampleForm()
```

**Comment by asch99** [comment] 2018-06-26 07:55
Just wondering, why not use 

ExampleForm(None if request.method=="GET" else request.form)

**Comment by davidism** [comment] 2018-06-26 12:04
You can do that as well, that's similar to what Flask-WTF does.

**Comment by davidism** [comment] 2018-06-26 12:04
Leaving this open as a docs issue.

**Comment by Cabalist** [comment] 2018-08-22 00:05
I am seeing this same issue in Flask-WTF 0.14.2 when inheriting from FlaskForm.  

@davidism you stated that this shouldn't be an issue there.    I'm curious if you could point out where it does this.  

(I am posting this here because it isn't necessarily a bug in Flask-WTF so much as this thread references a code example there)

**Comment by gudul** [comment] 2019-05-21 11:44
I think there is an additional issue: if this particular field is not present in the form (e.g. disabled BooleanField), the default value is not respected (always gets False value even if default value in self.data is True).
This patch worked for me:
`
    def process_formdata(self, valuelist):
        if not valuelist:
            if self.data is None: self.data = False
            return
        if valuelist[0] in self.false_values:
            self.data = False
        else:
            self.data = True
`

**Comment by azmeuk** [comment] 2019-08-06 12:25
An illustration of how this might be deceiving:
```python
>>> import werkzeug, wtforms
>>> class F(wtforms.form.Form):
...     boolean = wtforms.BooleanField()
... 
>>> class Obj:
...     boolean = True
... 
>>> F(None, Obj()).boolean.data
True
>>> F(werkzeug.ImmutableMultiDict(), Obj()).boolean.data
False
```

**Comment by azmeuk** [comment] 2020-10-04 16:10
Duplicate of #402

**Closed by azmeuk** 2020-10-04 16:10 UTC
