### ISSUE TITLE
Default values are ignored

### ISSUE THREAD

**Issue by Sebi2020** [wtforms/wtforms#611] opened 2020-05-28 16:15 UTC
Sometimes you need to set dynamic default values for fields. That makes it impossible to declare the defaults then you declare the class (not instance) member variables. wtforms ignores defaults, which are declared on instance fields.

### Actual Behavior
If you set defaults to the class **instance variables** wtforms completely ignores these values.
```python
# Paste a minimal piece of code that causes the problem. Here is an example:

from wtforms import Form,SelectMultipleField,StringField

class MyForm(Form):
    str_field = StringField("Name")
    sel_field = SelectMultipleField("Select")

def populate_form():
    aform = MyForm()
    aform.str_field.default = "hello" # ignored 
    
    aform.sel_field.choices = [("1","value1"),("2","value 2")]
    aform.sel_field.default = ['1'] # ignored
```

### Expected Behavior
The defaults should be rendered.

### Environment

* Python version: 3.6.9
* wtforms version: 2.3.1

**Comment by davidism** [comment] 2020-05-28 16:18
Duplicate of #371

**Closed by davidism** 2020-05-28 16:18 UTC
