### ISSUE TITLE
Validate whole form

### ISSUE THREAD

**Issue by Woolworths** [wtforms/wtforms#244] opened 2016-01-17 10:47 UTC
You should be able to validate the whole form without having to override validate().  
For example, what if I want to check if the email and password combination matches?
I could validate_email , but this doesn't really make sense, as I want to tell the end user an ambiguous message such as "wrong email password combination" (so people can't check if x.x@x.x is registered). Also you can't call your own function if it has a ValidationError in it, which it should. It has to be run by WTForms, or else it won't append to the errors, but it will show a whole error page. I don't really have any ideas to suggest, but it would be nice if this was worked on.

**Comment by davidism** [comment] 2018-06-13 00:39
Duplicate of #55

**Closed by davidism** 2018-06-13 00:39 UTC

**Comment by Woolworths** [comment] 2018-06-13 09:56
My bad, thank you.
