### ISSUE TITLE
Float fields don't accept 0 as a value when used with the DataRequired() validator

### ISSUE THREAD

**Issue by NixonInnes** [wtforms/wtforms#260] opened 2016-02-26 11:56 UTC
When a FloatField or IntegerField is defined with the DataRequired() validator, the form will not accept 0, or 0.0 as a valid entry. 
DataRequired() implies that an input is required in the form, and in many cases 0 would be a valid answer (i.e co-ordinates).

**Comment by lipis** [comment] 2016-02-28 18:06
#255

**Comment by crast** [comment] 2016-03-02 16:15
Closed as duplicate of #255

**Closed by crast** 2016-03-02 16:15 UTC
Labels: duplicate
