### ISSUE TITLE
in datetime-local, seconds is omitted in a case

### ISSUE THREAD

**Issue by miettal** [wtforms/wtforms#531] opened 2019-12-13 22:48 UTC
input type=datetime-local is can be set step attribute(like below).

    HTML template
    {{ form.start(class="form-control", step="1") }}
    (=> <input id="start" name="start" step="1" type="datetime-local" value="2019-12-14T00:00:00">)

    py code(reference)
    start = DateTimeLocalField('start', format='%Y-%m-%dT%H:%M:%S', default=datetime(...))

if you set like this↑, form text is shown like "2019/12/14 00:00:00".
but when submit, actually chrome sends "2019/12/14 00:00".
the second part(:00) was omitted.
probably if you set seconds part to 0 in HTML form, seconds part will be omitted.

Currently, WTForms provide format option, but not supported omitted case.

do you have a plan of omitted seconds support for format option?
or provide a high-level interface without using step attribute and format option?

chrome version: Version 79.0.3945.79 (Official Build) (64-bit)

**Comment by azmeuk** [comment] 2020-04-17 14:05
I could reproduce your issue:

```python
>>> import wtforms
>>> import datetime
>>> from tests.common import DummyPostData
>>> class F(wtforms.Form):
>>>    start = wtforms.fields.html5.DateTimeLocalField(format='%Y-%m-%dT%H:%M:%S')
>>> F(DummyPostData({"start": "2019-12-14T00:00:00"})).start.data
datetime.datetime(2019, 12, 14, 0, 0)
```
It seems to be the same issue than #508. What do you think?

**Comment by azmeuk** [comment] 2020-10-04 18:41
Duplicate of #508

**Closed by azmeuk** 2020-10-04 18:41 UTC
