### ISSUE TITLE
Python minimal version is wrong in FAQ / 3.0.1 changelog not published

### ISSUE THREAD

**Issue by JoKoT3** [wtforms/wtforms#752] opened 2022-08-10 14:36 UTC
FAQ Claims compatibility with python 3.6 : https://wtforms.readthedocs.io/en/3.0.x/faq/#what-versions-of-python-are-supported

Changelog does not exists for 3.0.1 : https://wtforms.readthedocs.io/en/3.0.x/changes/#version-3-0-0

**Comment by PanderMusubi** [comment] 2022-08-28 13:19
Perhaps because https://github.com/wtforms/wtforms/blob/master/src/wtforms/__init__.py#L7 was not bumped to 3.0.1?

Could a version 3.0.2 be published with this fixed and including PRs that have been merged or can be merged wasily.

**Comment by PanderMusubi** [comment] 2022-11-21 09:27
@azmeuk can you have a look at this one too? Thanks.

**Comment by azmeuk** [comment] 2023-07-22 08:19
Duplicate of #771

**Closed by azmeuk** 2023-07-22 08:19 UTC
