### ISSUE TITLE
ValueError: not enough values to unpack (expected 4, got 3)

### ISSUE THREAD

**Issue by guidoiaquinti** [wtforms/wtforms#814] opened 2023-10-23 13:08 UTC
I suspect commit `fada1110a6c8339c472ca5d5995dfb6960f27ee1` introduced in the `3.0.2` release, silently broke compatibility with https://flask-admin.readthedocs.io/en/latest/_modules/flask_admin/form/fields/#Select2Field

Code path:
```
else:
    for val, label, selected, render_kw in field.iter_choices():
        html.append(self.render_option(val, label, selected, **render_kw))
html.append("</select>")
return Markup("".join(html))
```

`field | <flask_admin.form.fields.Select2Field object at 0xffff73589a50>`
`flags | <wtforms.fields.Flags: {optional}>`
`html | [
'<select class="form-control" data-allow-blank="1" data-role="select2" id="locale" name="locale">'
]`
```
kwargs = {
  class: 'form-control', 
  data-allow-blank: '1', 
  data-role: 'select2', 
  id: 'locale'
}
```

### Environment

* Python version: `3.11`
* wtforms version: `3.0.1` works, `3.1.0` doesn't

**Comment by davidism** [comment] 2023-10-23 15:24
Duplicate of #811.

**Closed by davidism** 2023-10-23 15:24 UTC
