### ISSUE TITLE
Obtaining form data from multiple sources

### ISSUE THREAD

**Issue by fweep** [wtforms/wtforms#50] opened 2014-01-29 19:13 UTC
This is a feature request.

I'm using WTForms to validate JSON data. I know it's meant to process HTML forms, but it's nearly perfect for my JSON validation needs and I prefer its simplicity and syntax to other validation options.

I'd like to be able to provide multiple data sources to a form, and have the form combine them for validation purposes. The reason for this is to facilitate processing PATCH requests where only changed data is submitted.

For example, I'd like to do this:

`MyForm` validates two required fields: `name`, `age`

```
patch_data = dict(name="Joe")
existing_record_data = dict(name="Bob", age=30)
form = MyForm(formdata=patch_data, data=existing_record_data)
```

`form.validate()` would be true here, because `existing_record_data` contains `age`. I'd like a way to determine get just the `patch_data` fields back as well (after e.g. conversion to ints, etc.). I can already get patch data back via [WTForms-JSON](https://github.com/kvesteri/wtforms-json), but it'd be nice if that feature were in the core WTForms.

The docs for WTForms used to indicate that this sort of thing was possible, but have since been updated to clarify that if any `formdata` is provided, then `obj` and `data` are ignored.

If these are changes that you'd be willing to incorporate, I'd be willing to work on implementation.

**Comment by crast** [comment] 2015-12-15 08:41
Duplicate of #198

**Closed by crast** 2015-12-15 08:41 UTC
Labels: question
