### ISSUE TITLE
FormField with a field called 'name' bug

### ISSUE THREAD

**Issue by imti101** [wtforms/wtforms#634] opened 2020-07-08 16:15 UTC
### Actual Behavior

```python
# Paste a minimal piece of code that causes the problem. Here is an example:

>>> import wtforms
>>> class F(wtforms.Form):
...         name = wtforms.StringField()
...         id = wtforms.IntegerField()
>>> f = wtforms.Fieldlist(wtforms.FormField(F))
>>> print(f.name)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'str' object has no attribute 'name'
```

### Expected Behavior

`StringField` object at ....

### Environment

* Python version: 3.7
* wtforms version: 2.2.1

**Comment by davidism** [comment] 2020-07-08 16:34
Duplicate of #36

**Closed by davidism** 2020-07-08 16:34 UTC
