### ISSUE TITLE
on decimalfield

### ISSUE THREAD

**Issue by whb07** [wtforms/wtforms#426] opened 2018-06-27 12:20 UTC
What's the purpose of DecimalField generally? Coercing possible floats and strings that might look like a `decimal.Decimal` into one? What about the 'places' arguments for it? Is that the spot at which truncation should happen or otherwise ? Any tips and comments would be helpful 🤯

**Comment by davidism** [comment] 2018-06-27 17:11
I'm not sure what you mean. It's purpose is to take string input and create a `Decimal` object from it. It's no different than any other typed field in that regard.

**Comment by whb07** [comment] 2018-06-27 18:24
whats the argument `places` supposed to do? is it meant to set the decimal places to a certain spot?     

  i.e - `'23.23920320'` with `places=3` should be equal to `Decimal('23.239')` ?

**Comment by davidism** [comment] 2018-06-27 18:43
Presumably. There's an open issue, #101, that the arguments don't seem to work right now.

**Comment by whb07** [comment] 2018-06-27 21:15
heh....go figure. i was wondering if i was going crazy or something. i think i know how to patch it assuming it is not doing what its intended to. thanks! saved me the run around.

**Comment by davidism** [comment] 2018-06-27 21:17
Duplicate of #101

**Closed by davidism** 2018-06-27 21:17 UTC
Labels: question
