### ISSUE TITLE
Form-level errors

### ISSUE THREAD

**Issue by azmeuk** [wtforms/wtforms#571] opened 2020-04-19 15:12 UTC
As discussed in #568, it could be interesting to implement form-level errors. It has been suggested to:
- add a Form `form_errors` attribute that would be a list of errors
- make those errors be readable in `Form.errors[None]`

**Comment by davidism** [comment] 2020-04-22 03:56
Warehouse overrides the errors property to add form errors, see the third commit here: https://github.com/pypa/warehouse/pull/7826

**Comment by davidism** [comment] 2020-04-22 06:32
Duplicate of #55

**Closed by davidism** 2020-04-22 06:32 UTC
Labels: enhancement
