### ISSUE TITLE
Possibility to decouple from web-platform

### ISSUE THREAD

**Issue by Lewiscowles1986** [wtforms/wtforms#379] opened 2018-04-09 10:57 UTC
Would the project be open to decoupling some of the components from the HTTP/Web platform?

I Haven't used python for a while, but I've always used wtforms. A project I'm working on has both a web-module, and a cli-component and I was just thinking how valuable having the concept of forms could be for that, as well as GUI apps. 

I've looked at your dependencies and it looks like this isn't dependent on any third party validation, so all the power of WTForms is isolated to web-projects rather than modular and parts being able to be picked off from another repo.

Please excuse me if I have missed something, or if it's not something you'd be open to (even if I did it)

**Comment by ftm** [comment] 2018-06-12 18:15
This was a goal of the previous maintainer for a future version of WTForms, I'm not sure whether @davidism is still planning on doing this at some point?

**Comment by davidism** [comment] 2018-06-12 19:57
Yes, I still want this.

**Comment by Lewiscowles1986** [comment] 2018-06-13 09:57
Are there notes on blockers to #234 outside of that issue?

**Comment by davidism** [comment] 2018-06-25 13:11
No blockers, just need to come up with a good design. Closing this as a duplicate of #234.

**Closed by davidism** 2018-06-25 13:11 UTC
Labels: enhancement, epic
