### ISSUE TITLE
Validation fails on required boolean fields when they have valid data

### ISSUE THREAD

**Issue by drakkhen** [wtforms/wtforms#646] opened 2020-09-01 21:29 UTC
When a required boolean field is set to False, validation fails.  I would expect validation to fail if the field's value was NOT set, or something other than a boolean value.  But a required boolean field should validate successfully if it's set to True or False.

### Actual Behavior

```python
Python 3.8.5 (default, Jul 21 2020, 10:48:26)
[Clang 11.0.3 (clang-1103.0.32.62)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import wtforms
>>> wtforms.__version__
'2.3.3'
>>> class F(wtforms.Form):
...      foo = wtforms.BooleanField('Has Foo', [wtforms.validators.InputRequired()])
...
>>> f = F(foo=False)
>>> f.validate()
False

```

### Expected Behavior

```python
Python 3.8.5 (default, Jul 21 2020, 10:48:26)
[Clang 11.0.3 (clang-1103.0.32.62)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import wtforms
>>> wtforms.__version__
'2.3.3'
>>> class F(wtforms.Form):
...      foo = wtforms.BooleanField('Has Foo', [wtforms.validators.InputRequired()])
...
>>> f = F(foo=False)
>>> f.validate()
True
```

### Environment

* Python version:  3.8.5
* wtforms version:  2.3.3

**Comment by azmeuk** [comment] 2020-10-04 13:33
Duplicate of #402

**Closed by azmeuk** 2020-10-04 13:33 UTC
