### ISSUE TITLE
MultipleFileField only sends the last file to the server

### ISSUE THREAD

**Issue by t3ndai** [wtforms/wtforms#617] opened 2020-06-05 21:07 UTC
### Actual Behavior

```python
class CreateItemForm(FlaskForm):
    upload = MultipleFileField('Upload Images or Files',
        validators=[
            Optional(),
            FileAllowed(['jpg', 'png', 'txt', 'pdf'], 'Text and Images only!'),
        ]
    )
    content = HiddenField('content', validators=[Optional(), validate_upload_or_text])
    submit = SubmitField('Create')
```

```html
    <form action="" method="POST" enctype="multipart/form-data">
```

using wtforms through flask-wtf and i'm seeing that the upload file which is currently using a single MultipleFileField only sends the last uploaded file to the server 

### Expected Behavior

```python
# Show us, and explain what behavior you would have expected.
# Here is an example:
if form.validate_on_submit():
    for file in form.upload.data:
        current_app.logger.info('%s filename', file.filename)

```
i.e have the filenames of all the files uploaded 

### Environment

* Python version: 3.8
* wtforms version: latest

**Comment by azmeuk** [comment] 2020-10-07 15:16
I could not reproduce with wtforms alone:

```python
>>> import wtforms
>>> from werkzeug.datastructures import ImmutableMultiDict
>>> class CreateItemForm(wtforms.Form):
...     upload = wtforms.MultipleFileField(
...         validators=[
...             wtforms.validators.Optional(),
...         ]
...     )
>>> f = CreateItemForm(ImmutableMultiDict({"upload": ["a.jpg", "b.jpg", "c.jpg"]}))
>>> for file in f.upload.data:
...     file
a.jpg
b.jpg
c.jpg
```

**Comment by azmeuk** [comment] 2020-10-07 15:33
Could reproduce with flask-wtf neither.

```python
>>> from werkzeug.datastructures import MultiDict
>>> import flask
>>> import wtforms
>>> import flask_wtf
>>> import flask_wtf.file
>>> class CreateItemForm(flask_wtf.FlaskForm):
...     upload = wtforms.MultipleFileField(
...         validators=[
...             wtforms.validators.Optional(),
...         ],
...     )
>>> app = flask.Flask("test")
>>> app.config["SECRET_KEY"] = "foobar"
>>> with app.test_request_context():
...     f = CreateItemForm(MultiDict({"upload": ["a.jpg", "b.jpg", "c.jpg"]}))
...     f.validate()
...     assert not f.upload.errors
...     for file in f.upload.data:
...         file
a.jpg
b.jpg
c.jpg
```
I am closing this ticket, but we can re-open it if you can write a reproducible test case. Ideally something one can blindly paste into a python terminal and observe the bug you describe.

**Closed by azmeuk** 2020-10-07 15:33 UTC
