### ISSUE TITLE
Date formats

### ISSUE THREAD

**Issue by Garito** [wtforms/wtforms#264] opened 2016-03-13 10:33 UTC
Hi!
I'm using HTML5 DateTimeLocalField because it is the only one that renders the correct datetime picker on mobile (you need to add a picker for desktop) but I'm encountering the typical date format issue so I came here to add and issue 

But there are two already about that:
One from myself: https://github.com/wtforms/wtforms/issues/210
Another from @italomaia: https://github.com/wtforms/wtforms/issues/175

Today is the 1st birthday for the 2nd on meaning that has been one year with this one unsolved
Both are marked as enhancement when they are really bugs

With my locale, firefox and safari sends "%d/%m/%Y %H:%M" but chrome sends "%Y.%m-%dT%H:%M" (notice that firefox and safari respects the local datetime with my locale but chrome sends an almost valid iso8601: it lacks the Z cause it is not UTC)

So, with this issue, how do you expect we solve this particularity?
Another question will be: what cycle of update we need to expect from this library?
Is there any properly updated fork or we must to change to another library? I understand that as open source the maintainers has no responsability on this kind of problems but I need to advance by changing the library or extend it by myself
What do you expect we do with this issue?

**Comment by davidism** [comment] 2018-06-13 00:32
Duplicate of #175

**Closed by davidism** 2018-06-13 00:32 UTC
