### ISSUE TITLE
URL validator does not accept basic auth

### ISSUE THREAD

**Issue by bm371613** [wtforms/wtforms#152] opened 2015-01-09 11:50 UTC
>>> from wtforms import *
    >>> class UrlForm(Form):
    ...     url = StringField(validators=[validators.URL()])
    ... 
    >>> form = UrlForm(url="https://foo:password@example.com")
    >>> form.validate()
    False

**Comment by crast** [comment] 2015-01-24 22:06
Duplicate of #153

**Closed by crast** 2015-01-24 22:06 UTC
Labels: duplicate
