### ISSUE TITLE
DateTime Fields don't populate correctly

### ISSUE THREAD

**Issue by Garito** [wtforms/wtforms#210] opened 2015-07-22 10:35 UTC
Hi!
I have a form with DateTimeLocalField that renders ok and sends to the server the correct value but when I try to call the form with the request.form the field is set to None. I've tryed with DateTimeField with the same result

Could someone explain this behaviour? Need more info?

Thanks!

**Comment by Garito** [comment] 2015-07-22 11:11
Seems to be the format of the date: https://github.com/wtforms/wtforms/blob/master/wtforms/fields/core.py#L735

By this code, is pretty clear we can't set several formats (thinking in locale)

Is there a way to set all the valid formats or do I need to change it by locale?

Thanks!

**Comment by davidism** [comment] 2018-06-13 00:33
Duplicate of #175

**Closed by davidism** 2018-06-13 00:33 UTC
Labels: enhancement
